Add "struct".
Otherwise, with bazel 0.28.0, I get:

    ERROR: failed to execute WORKSPACE file: ...: cannot load @bazel_tools//tools/build_defs/repo:git.bzl: cannot load :git_worker.bzl: @bazel_tools//tools/build_defs/repo:git_worker.bzl:96:12: undefined: struct

I think "struct" was added to skylark recently:
https://docs.bazel.build/versions/master/skylark/lib/struct.html.